name: test

on: workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types: [created]

concurrency:
  group: "testnet"
  cancel-in-progress: true

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          
      - name: Yarn install
        run: |
          yarn install --dev
          yarn hint
          yarn install --production
          

      - name: Run Forge tests
        run: |
          forge test -vvv --gas-report
        id: test
